# -*- coding: utf-8 -*-
"""CODIGO_EXAMEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_7fgzZ_BvLVS2DRrAyHpHQ-i6FreK1e
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tempo.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# 
# st.write(''' # PREDICCION DE LA TEMPERATURA EN MÉXICO ''')
# st.image("tempoo.jpeg", caption="RODRIGO SÁNCHEZ ACOSTA - A1615173 : Esta app esta diseñada para calcular la temperatura media de ciertas ciudades de la Republica Mexicana")
# 
# st.header('ASPECTOS A CONSIDERAR')
# 
# def user_input_features():
#   city = st.number_input( "Ciudad (0 = Acapulco, 1 = Aguascalientes, 2 = Acuña):",  min_value=0, max_value=2, value=0, step=1)
#   year = st.number_input("Año:",min_value=1800, max_value=2050, value=1900, step=1)
#   month = st.number_input("Mes (1 a 12):",ccmin_value=1, max_value=12, value=1, step=1)
# 
# 
# 
#   user_input_data = { "city": city,
#                       "year": year,
#                       "month": month
#                      }
# 
#   features = pd.DataFrame(user_input_data, index=[0])
# 
#   return features
# 
# df = user_input_features()
# 
# datos =  pd.read_csv('quizz3', encoding='latin-1')
# X = datos["City", "Year", "Month"]
# y = datos["AverageTemperature"]
# 
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1615173)
# LR = LinearRegression()
# LR.fit(X_train,y_train)
# 
# b1 = LR.coef_
# b0 = LR.intercept_
# prediccion = b0 + b1[0]*df['City'] + b1[1]*df['Year'] + b1[2]*df['Month']
# 
# st.subheader("CALCULO DE LA TEMPERATURA PROMEDIO")
# st.write('LA PREDICCION DE LA TEMPERATURA PROMEDIO ES :', prediccion)